version: '3.5'

networks:
  playground-network:
    name: playground-network
    driver: bridge

services:

  db:
    container_name: playground_dev_db
    image: mysql:latest
    restart: always
    volumes:
      - mysql-playground:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    networks:
      - playground-network

  api:
    stdin_open: true
    build:
      context: .
      dockerfile: ./api/Dockerfile.dev
      args:
        - NODE_ENV=development
    container_name: playground_dev_api
    env_file:
      - .env
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api:/app/api/
      - ./prisma:/app/prisma/
    networks:
      - playground-network

volumes:
  mysql-playground: {}