version: '3.5'

networks:
  playground-network:
    name: playground-network
    driver: bridge

services:

  db:
    container_name: playground_dev_db
    image: mysql:latest
    restart: always
    volumes:
      - playground-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    networks:
      - playground-network

  api:
    container_name: playground_dev_api
    build:
      context: .
      target: development
    restart: always
    volumes:
      - ./api:/srv/apps/api/
      - ./prisma:/srv/apps/prisma/
      - playground-node_modules:/srv/apps/node_modules
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - playground-network

  prisma:
    container_name: playground_prisma
    build:
      context: .
      target: base
    env_file:
      - .env
    entrypoint: [ "npx prisma" ]
    networks:
      - playground-network

volumes:
  playground-mysql: 
  playground-node_modules: