version: '3.5'

networks:
  playground-docker:
    name: playground-docker
    driver: bridge

services:

  db:
    container_name: playground_db
    image: mysql:latest
    restart: always
    volumes:
      - mysql-playground:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - playground-docker

volumes:
  mysql-playground: {}