version: '3.5'

networks:
  backend_network:
    name: backend_network
    driver: bridge

services:

  db:
    container_name: playground_dev_db
    image: mysql:latest
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    networks:
      - backend_network

  api:
    container_name: playground_dev_api
    build:
      context: .
      target: development
    restart: always
    volumes:
      - ./api:/srv/apps/api/
      - ./prisma:/srv/apps/prisma/
      - node_modules:/srv/apps/node_modules
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - backend_network

  npx:
    build:
      context: .
      target: npx
    env_file:
      - .env
    networks:
      - backend_network

volumes:
  mysql: 
  node_modules: