networks:
  playground:
    name: playground
    driver: bridge

services:

  db:
    image: mysql:latest
    container_name: ${MYSQL_HOST}
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    networks:
      - playground

  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
      target: development
    volumes:
      - ./services/api:/usr/src/services/api
      - /usr/src/node_modules
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - playground

  client:
    build:
      context: .
      dockerfile: ./services/client/Dockerfile
      target: development
    volumes:
      - ./services/client:/usr/src/services/client
      - /usr/src/node_modules
    env_file:
      - .env
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    stdin_open: true
    command: [ "run", "client:dev" ]

volumes:
  mysql: