version: '3.5'

networks:
  playground:
    name: playground
    driver: bridge

services:

  db:
    container_name: playground_dev_db
    image: mysql:latest
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    networks:
      - playground
      
  app:
    container_name: playground_app
    build:
      context: .
      target: development
    restart: always
    volumes:
      - .:/usr/src/
      - /node_modules
    env_file:
      - .env
    ports:
      - ${API_PORT}:80
      - ${CLIENT_PORT}:80
    networks:
      - playground

volumes:
  mysql: