FROM debian:buster-slim as wait-for-it

# Get wait for it script
RUN apt-get update && apt-get install -y wait-for-it

FROM node:lts-alpine3.14

WORKDIR /app

ARG NODE_ENV

ENV NODE_ENV=${NODE_ENV} MYSQL_URL=${MYSQL_URL}

COPY --from=wait-for-it /usr/bin/wait-for-it .

COPY .entrypoint/entrypoint.sh  package*.json tsconfig*.json .env ./

COPY api/package*.json api/tsconfig.json ./api/

# Set chmod and Install dependencies
RUN apk add --no-cache --upgrade bash \
    && npm install \
    && chmod +x ./entrypoint.sh \
    && chmod +x ./wait-for-it

EXPOSE ${API_PORT}

ENTRYPOINT [ "./entrypoint.sh" ]